Validate CMake release number in preprelease
See https://trello.com/c/cc8k892c for details.

diff --git a/buildtools/preprelease b/buildtools/preprelease
--- a/buildtools/preprelease
+++ b/buildtools/preprelease
@@ -30,11 +30,12 @@
 #
 
 DROPBOXDIR=$(jq  -r .personal.path ~/.dropbox/info.json)
+PRERELDIR=${DROPBOXDIR}/Public/builds/Prereleases
 RELEASEDIR=${DROPBOXDIR}/Public/builds/Releases
 SHAPAT='^[0-9a-f]{64} '
 
 
-# Figure out which Assimilation release has been built
+# Figure out which Assimilation package release has been built
 infer_assimrelease() {
     pkgdir=$1
     prefix='assimilation-cma-'
@@ -58,7 +59,7 @@ infer_all_assim_releases() {
     done
 }
 # Make sure all our packages are for the same Assimilation release
-verify_assim_relno_consistency() {
+verify_package_relno_consistency() {
     builddir=${1-.}
     prevrel=''
     rc=0
@@ -85,13 +86,13 @@ get_git_hash_info() {
 # Report all the git hash signatures for complaints
 report_git_hash_info() {
     builddir=${1-.}
-    prevhash=''
     for dir in $(find ${builddir} -type d -name packages -print)
     do
         hash=$(get_git_hash_info "$dir/build.out")
         printf 'Git hash [%7s] for %s\n' "$hash" "$dir"
     done
 }
+
 
 
 # Make sure all our packages are built from the same git version
@@ -112,6 +113,52 @@ verify_git_hash_consistency() {
         prevhash=$hash
     done
     return 0
+}
+
+get_cmake_rel_info() {
+    dir=${1-.}
+    test -f $dir/build.out
+    REL=$(grep '^ASSIMVERSION='  $dir/build.out | sed -e 's%.*= *%%')
+    echo $REL | sed 's%\.[^.]*$%%'
+}
+
+report_cmake_rel_info() {
+    for dir in $(find ${builddir} -type d -name packages -print)
+    do
+        echo "$dir: $(get_cmake_rel_info $dir)"
+    done
+}
+
+verify_cmake_rel_consistency() {
+    prevrel=''
+    for dir in $(find ${builddir} -type d -name packages -print)
+    do
+        rel=$(get_cmake_rel_info $dir)
+        if
+            [ ! -z "$prevrel" -a "$prevrel" != "$rel" -o -z "$rel" ]
+        then
+            echo "OOPS: CMake versions are inconsistent." >&2
+            report_cmake_rel_info $builddir
+            return 1
+        fi
+        prevrel=$rel
+    done
+    return 0
+}
+
+compare_cmake_to_pkg_version() {
+    dir=$(find ${builddir} -type d -name packages -print |head -n 1)
+    cmakerel=$(get_cmake_rel_info $dir)
+    pkgrel=$(infer_assimrelease $dir)
+    if
+        [ "$cmakerel" != "$pkgrel" ]
+    then
+        echo "CMake release is $cmakerel but package release is $pkgrel." >&2
+        return 1
+    else
+        : echo "CMake release is $cmakerel and package release is $pkgrel."
+        return 0
+    fi
 }
 
 # Return the OS information from the build - what OS was it built on?
@@ -146,23 +193,24 @@ verify_checksums() {
     rc=0
     for dir in $(find ${builddir} -type d -name packages -print)
     do
-        if (
-            if
-                [ ! -f $dir/build.out ]
-            then
-                continue
-            fi
-            cd $dir
-            if
-                egrep "${SHAPAT}" < build.out | sha256sum -c --status
-            then
-                : "OK checksumd in $dir"
-            else
-                echo "Failed checksums for files in $dir:"
-                egrep '^[0-9a-f]{64} ' < build.out | sha256sum -c --quiet
-                exit 1
-            fi
-          )
+        if
+            [ ! -f $dir/build.out ]
+        then
+            continue
+        fi
+        if
+            (
+                cd $dir
+                if
+                    egrep "${SHAPAT}" < build.out | sha256sum -c --status
+                then
+                    : "OK checksums in $dir"
+                else
+                    echo "Failed checksums for files in $dir:"
+                    egrep '^[0-9a-f]{64} ' < build.out | sha256sum -c --quiet
+                    exit 1
+                fi
+            )
         then
           : "OK checksums in $dir"
         else
@@ -175,8 +223,9 @@ verify_checksums() {
 # Verify all the release pieces are complete and consistent with each other
 verify_release_consistency() {
     ourrc=0
-    for method in verify_assim_relno_consistency verify_git_hash_consistency  \
-        verify_os_release_info verify_checksums
+    for method in verify_package_relno_consistency  \
+        verify_git_hash_consistency verify_os_release_info verify_checksums \
+        verify_cmake_rel_consistency compare_cmake_to_pkg_version
     do
         if
             $method
@@ -213,11 +262,35 @@ copy_release_to_dropbox() {
         for file in $(egrep "${SHAPAT}" < $buildout | cut -c66-)
         do
             test -d $NEWRELDIR/$relsubdir || mkdir $NEWRELDIR/$relsubdir
-            cp $pkgdir/$file $NEWRELDIR/$relsubdir/
+            cp -p $pkgdir/$file $NEWRELDIR/$relsubdir/
         done
-        cp $pkgdir/build.out $NEWRELDIR/$relsubdir/
+        cp -p $pkgdir/build.out $NEWRELDIR/$relsubdir/
     done
 }
+usage() {
+    name=$(basename $1)
+    cat <<-!EOF
+		usage: $name [--prerelease]
+
+		$name prepares a release (or prerelease) from currently built objects
+		and installs them under dropbox on the current machine.
+		!EOF
+}
+
+if
+    [ $# -gt 0 ]
+then
+    case $1 in
+        --prerelease)   RELEASEDIR=$PRERELDIR
+                        ;;
+        -h|--help)      usage "$0"
+                        exit 0
+                        ;;
+        *)              usage "$0"
+                        exit 1
+                        ;;
+    esac
+fi
 
 if 
     verify_release_consistency
