Added code to complain and exit if there's no sshd config file installed.

diff --git a/discovery_agents/sshd b/discovery_agents/sshd
--- a/discovery_agents/sshd
+++ b/discovery_agents/sshd
@@ -156,6 +156,12 @@ fmtitem() {
 }
 
 discover() {
+    if
+        [ ! -f "$SSHD_CONFIG" -o  ! -r  "$SSHD_CONFIG" ]
+    then
+        echo "Cannot discover sshd configuration - cannot read $SSHD_CONFIG" >&2
+        exit 1
+    fi
     prefix="    "
     cat <<-!
 	{
