I now generate the Dockerfile for CentOS6 using the new CentOS6-directions command and the dockit command which calls it.

diff --git a/docker/CentOS/CentOS6-directions b/docker/CentOS/CentOS6-directions
--- a/docker/CentOS/CentOS6-directions
+++ b/docker/CentOS/CentOS6-directions
@@ -1,143 +1,351 @@
-BUILDREQS="rpm-build tar scl-utils-build glib2-devel libpcap-devel zlib-devel gcc scl-utils python27-python python27-python-devel cmake28 python27-python-setuptools"
-BUILDREQS_2="python27-python-setuptools"
+#!/bin/sh
+# vim: smartindent tabstop=4 shiftwidth=4 number
+#
+#
+#	CentOS6-directions -- File to give directions for building us on top of CentOS 6
+#							in a variety of formats - scripts, documentation, etc.
+#
+# This file is part of the Assimilation Project.
+#
+# Author: Alan Robertson <alanr@unix.sh>
+# Copyright (C) 2014 - Assimilation Systems Limited
+#
+# Free support is available from the Assimilation Project community - http://assimproj.org
+# Paid support is available from Assimilation Systems Limited - http://assimilationsystems.com
+#
+# The Assimilation software is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# The Assimilation software is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with the Assimilation Project software.  If not, see http://www.gnu.org/licenses/
+set -e
+#
+#
+# It is possible these might eventually need to change
+NEOVERSION=2.1.3
+JAVA="java-1.7.0-openjdk"
 LOGGER=rsyslog
+CENTOSVERS="centos:centos6"
+#
+# The rest is less malleable - but also could change as the project matures
+#
+CMAKE=cmake28
+PYSCL=python27
+BUILDREQS="rpm-build tar scl-utils-build glib2-devel libpcap-devel zlib-devel gcc scl-utils $PYSCL-python $PYSCL-python-devel $CMAKE $PYSCL-python-setuptools"
+BUILDREQS_2="$PYSCL-python-setuptools"
 EZINST="pip"
 PIPBUILD="ctypesgen"
 PIPRUN="py2neo netaddr getent flask"
+# Python packages we only need for testing
 PIPTEST="testify pylint"
-TESTREQS="mercurial valgrind"
-JAVA="java-1.7.0-openjdk"
-NEO4J_DEPS="which lsof"
-NEOVERSION=2.1.3
+# RPMs we only need for testing
+TESTREQS="valgrind"
+NEO4J_DEPS="which lsof tar"
 NEOPARENT=/var/lib
 NEODIR=$NEOPARENT/neo4j
 NEOEDITION=community
+NEOSERVICE=neo4j-service
 ASSIMVERS=tip
 ASSIMURL=http://hg.linux-ha.org/assimilation/archive/${ASSIMVERS}.tar.gz
 EPELURL=http://mirror-fpt-telecom.fpt.net/fedora/epel/6/i386/epel-release-6-8.noarch.rpm
 SCLREPO=http://dev.centos.org/centos/6/SCL/scl.repo
 ARCH=x86_64
-#NEO4JYUM=http://yum.neo4j.org
+NEO4JYUM=http://yum.neo4j.org
 RPMSRCDIR=/rpmbuild/SOURCES
 TARBALL=$RPMSRCDIR/assim.${ASSIMVERS}.tgz
 
 enable_repos() {
   cat <<-!
-	echo "Enabling CentOS 6 EPEL repo"
+	# Enable the CentOS 6 EPEL and SCL repos"
 	yum -y install wget
 	wget -q http://mirror-fpt-telecom.fpt.net/fedora/epel/6/i386/epel-release-6-8.noarch.rpm -O /tmp/epel-release-6-8.noarch.rpm
 	yum -y install /tmp/epel-release-6-8.noarch.rpm
 	rm -f /tmp/epel-release-6.8.noarch.rpm
-	echo "Enabling CentOS 6 SCL repo"
 	wget -qO- http://dev.centos.org/centos/6/SCL/scl.repo >> /etc/yum.repos.d/centos.scl.repo
 	yum -y update
-
 	!
 }
 
-download_tarball_steps() {
+download_tarball() {
   cat <<-!
-	echo "Downloading tarball \"${ASSIMVERS}\" from Assimilation source control"
+	# Download the Assimilation tarball "${ASSIMVERS}" from project source control
 	mkdir -p $RPMSRCDIR
 	wget -q -O ${TARBALL} ${ASSIMURL}
-
 	!
 }
 
-rpm_build_steps() {
+rpm_build() {
   cat <<-!
-	echo "Building the Assimilation RPMs for ${ARCH} from project tarball"
+	# Build the Assimilation RPMs for ${ARCH} from the project tarball
 	yum -y install $BUILDREQS
 	cd $RPMSRCDIR
-	toptardir=\$(tar tzf ${TARBALL} | head -1 | sed 's%/.*%%')
-	version=\$(echo \$toptardir)
-	echo "Downloaded Assimilation version \$version"
+	ASSIMVERSION=\$(tar tzf ${TARBALL} | head -1 | sed 's%/.*%%')
+	echo "Downloaded Assimilation version \${ASSIMVERSION}"
 	mkdir /tmp/assim-rpm
 	cd /tmp/assim-rpm
-	tar xvf ${TARBALL} \${toptardir}/docker/CentOS/assimilation-cma.spec
+	tar xvf ${TARBALL} \${ASSIMVERSION}/docker/CentOS/assimilation-cma.spec
 	rm -f /rpmbuild/RPMS/${ARCH}/assimilation-*.rpm
-	mv $TARBALL $RPMSRCDIR/\${toptardir}.tgz
-	scl enable python27 'easy_install pip'
-	scl enable python27 'pip install ${PIPBUILD}'
-	rpmbuild -ba /tmp/assim-rpm/\${toptardir}/docker/CentOS/assimilation-cma.spec --define="assimversion \${version}"
-	#cd /
-	#rm -fr /tmp/assim-rpm
-	# RPM build complete
-
+	mv $TARBALL $RPMSRCDIR/\${ASSIMVERSION}.tgz
+	scl enable $PYSCL 'easy_install pip'
+	scl enable $PYSCL 'pip install ${PIPBUILD}'
+	rpmbuild -ba /tmp/assim-rpm/\${ASSIMVERSION}/docker/CentOS/assimilation-cma.spec --define="assimversion \${ASSIMVERSION}"
+	cd /
+	rm -fr /tmp/assim-rpm
+	!
+}
+manual_package_download() {
+  cat <<-!
+	# Manual steps to download packages from the Assimilation Dropbox site
+	Select the version you want to install (later is typically better), and click on that version
+	Click on the directory that corresponds to your OS
+	Save the packages that you want to install - may need to right-click and [Save As]. Only one system needs the CMA package -
 	!
 }
 
-java_install_steps() {
+java_install() {
   cat <<-!
-	echo "Installing JAVA ${JAVA}"
+	# Install JAVA from ${JAVA}
 	yum -y install ${JAVA}
-	# JAVA install complete
-
 	!
 }
-neo4j_install_steps() {
+neo4j_install() {
   cat <<-!
-	echo "Installing Neo4j ${NEOEDITION} edition version ${NEOVERSION}"
+	# Install the ${NEOEDITION} edition of Neo4j version ${NEOVERSION}
 	yum -y install ${NEO4J_DEPS}
 	wget -q -O /tmp/neo4j-${NEOEDITION}-${NEOVERSION}-unix.tar.gz "http://download.neo4j.org/artifact?edition=${NEOEDITION}&version=${NEOVERSION}&distribution=tarball"
 	tar -C $NEOPARENT -xzf /tmp/neo4j-${NEOEDITION}-${NEOVERSION}-unix.tar.gz
 	ln -s $NEOPARENT/neo4j-${NEOEDITION}-${NEOVERSION}/ $NEODIR
-	(echo ''; echo '') | ${NEODIR}/bin/neo4j-installer install
-	# Neo4j install complete
-
+	printf '\n\n' | ${NEODIR}/bin/neo4j-installer install
 	!
 }
-rpm_install_steps() {
+
+neo4j_rpm_install() { # This RPM is currently broken!
   cat <<-!
-	echo "Installing the Assimilation RPMs for CentOS6"
-	yum -y install python27-python-setuptools
-	scl enable python27 'easy_install pip'
-	scl enable python27 'pip install ${PIPRUN}'
+	# Install the ${NEOEDITION} edition RPM of Neo4j version ${NEOVERSION}
+	wget http://debian.neo4j.org/neotechnology.gpg.key -O /tmp/neo4j.key
+	rpm --import /tmp/neo4j.key
+	rm -f /tmp/neo4j.key
+	cat <<-!REPO > /etc/yum.repos.d/neo4j.repo
+		[neo4j]
+		name=Neo4j Yum Repo
+		baseurl=$NEO4JYUM
+		enabled=1
+		gpgcheck=1
+	!REPO
+	yum -y install neo4j
+	!
+}
+
+cma_rpm_install() {
+  cat <<-!
+	# Install the CentOS 6 Assimilation RPMs for the CMA
+	yum -y install $PYSCL-python-setuptools
+	scl enable $PYSCL 'easy_install pip'
+	scl enable $PYSCL 'pip install ${PIPRUN}'
+	yum -y install assimilation-cma*.${ARCH}.rpm
+	!
+}
+nanoprobe_rpm_install() {
+  cat <<-!
+	# Install the CentOS 6 Assimilation RPMs for the nanoprobe
 	cd /rpmbuild/RPMS/${ARCH}/ # Or whereever you have the RPMs
-	ls assimilation-*.rpm
-	yum -y install assimilation-nanoprobe*.${ARCH}*.rpm install assimilation-cma*.${ARCH}*.rpm
-	# RPM install complete!
-
+	yum -y install assimilation-nanoprobe*.${ARCH}.rpm
 	!
 }
-logger_install_steps() {
+
+
+logger_install() {
   cat <<-!
-	echo "Installing and starting logger ${LOGGER}"
+	# Install and start ${LOGGER} logger
 	yum -y install ${LOGGER}
-	# ${LOGGER} install complete!
-
 	!
 }
-	
+build_for_test() {
+  cat <<-!
+	# (re-)Build the Assimilation software for testing
+    set -x
+	mkdir /tmp/assimilation-test /tmp/assimilation-test/bin
+	cd /tmp/assimilation-test
+    tar xzf $RPMSRCDIR/\${ASSIMVERSION}.tgz
+	mv \${ASSIMVERSION} src
+    cd /tmp/assimilation-test/bin
+    /usr/bin/${CMAKE} ../src
+    scl enable $PYSCL make
+	!
+}
 
-echo "set -e"
-enable_repos
-download_tarball_steps
-rpm_build_steps
-java_install_steps
-neo4j_install_steps
-rpm_install_steps
-logger_install_steps
-exit 0
+run_assimilation_tests() {
+  cat <<-!
+	# Run the Assimilation unit tests
+	yum -y install ${TESTREQS}
+	scl enable $PYSCL 'pip install ${PIPTEST}'
+	mkdir -p /var/lib/heartbeat/lrm
+    cd /tmp/assimilation-test/src/cma
+    service $LOGGER start 
+	service ${NEOSERVICE} start 
+	sleep 10
+	scl enable $PYSCL 'testify -v tests'
+	!
+}
 
-############### Get rid of cruft starting from here...
+#mkdir -p /var/lib/heartbeat/lrm
 
-RUN yum -y install python27-python python27-python-setuptools python27-python-devel
-RUN echo "about to build another new version (v53)"
-RUN mkdir -p /root/assimilation/src /root/assimilation/bin && hg clone http://hg.linux-ha.org/assimilation /root/assimilation/src
-RUN cd /root/assimilation/src && id=$(hg id --id .) && mkdir -p /rpmbuild/SOURCES && hg archive --type tgz /rpmbuild/SOURCES/${id}.tgz && rpmbuild -ba /root/assimilation/src/docker/CentOS/assimilation-cma.spec --define="assimversion ${id}"
-RUN cd /root/assimilation/bin; /usr/bin/cmake28 ../src && scl enable python27 "make install"
-#EXPOSE 55604 7473 7474 1984 1337
-###  Neo4j RPM
-RUN wget http://debian.neo4j.org/neotechnology.gpg.key -O /tmp/neo4j.key  && rpm --import /tmp/neo4j.key && rm -f /tmp/neo4j.key
-#RUN echo '[neo4j]' > /etc/yum.repos.d/neo4j.repo && echo 'name=Neo4j Yum Repo' >> /etc/yum.repos.d/neo4j.repo && echo 'baseurl=http://yum.neo4j.org' >> /etc/yum.repos.d/neo4j.repo && echo 'enabled=1' >> /etc/yum.repos.d/neo4j.repo && echo 'gpgcheck=1' >> /etc/yum.repos.d/neo4j.repo && yum -y install neo4j && mkdir -p /var/lib/heartbeat/lrm
+step_map() {
+   cat <<-!STEPMAP
+docker enable_repos download_tarball java_install neo4j_install rpm_build nanoprobe_rpm_install cma_rpm_install logger_install build_for_test run_assimilation_tests
+install_prebuilt_cma java_install neo4j_install manual_package_download cma_rpm_install nanoprobe_rpm_install
+install_prebuilt_nanoprobe manual_package_download nanoprobe_rpm_install
+create_docker_cma java_install neo4j_install cma_rpm_install
+create_docker_nanoprobe nanoprobe_rpm_install
+!STEPMAP
+}
+get_task_list() {
+    step_map | grep "^$1 " | cut -d' ' -f2-
+}
 
-ENV BROKENDNS true
-RUN echo "/usr/lib*/assimilation" > /etc/ld.so.conf.d/assimilation.conf && ldconfig /usr/lib*/assimilation
+create_task_script() {
+    echo "set -e"
+    for task in $(get_task_list "$1")
+    do
+        $task
+        echo ""
+    done
+}
 
-# An alternative to starting syslog would be to mount /dev/log from the host - but you can't do that in a Dockerfile :-(
-RUN scl enable python27 'pip install testify'
-RUN NEO=neo4j-service; cd /root/assimilation/src/cma && (rsyslogd&  /etc/init.d/${NEO} start) && sleep 15 && scl enable python27 '/usr/bin/env python --version; testify -v tests'
-###  Our RPMs
-# These are only here to make Alan happy
-RUN scl enable python27 'pip install flask pylint'
+create_doxygen_docs() {
+    for task in $(get_task_list "$1")
+    do
+        $task | (
+            read task_description
+            description=$(echo "$task_description" | sed 's%^# *%%')
+            printf ' -# <b>%s</b>\n' "$description"
+            while
+                read step_text
+            do
+                printf '  -# <tt>%s</tt>\n' "$step_text"
+            done
+        )
+    done
+}
+
+create_asciidoc() {
+	printf '.Ordered\n'
+    for task in $(get_task_list "$1")
+    do
+        $task | (
+            read task_description
+            description=$(echo "$task_description" | sed 's%^# *%%')
+            printf '.*%s*\n' "$description"
+            while
+                read step_text
+            do
+				case $step_text in
+					\#*)	step_text=$(echo "$step_text" | sed 's%^# *%%')
+							printf '_%s_\n'	"$step_text";;
+					*)		printf '..+%s+\n' "$step_text";;
+				esac
+            done
+        )
+    done
+	printf '\n'
+}
+
+
+create_dockerfile() {
+	printf 'FROM %s\n' $CENTOSVERS
+	printf "# Created by %s --format=dockerfile %s\n" "$0" "$1"
+    for task in $(get_task_list "$1")
+    do
+        $task | (
+            read task_description
+            description=$(echo "$task_description" | sed 's%^# *%%')
+            printf '# %s: %s\n' "$task" "$description"
+            while
+                read word morestuff
+            do
+				case $word in
+				  \#*)				printf '%s %s\n'				"$word $morestuff";;
+				  cd)				printf 'WORKDIR %s\n'			"$(echo $morestuff| sed 's%#.*%%')";;
+				  ASSIMVERSION=*)		printf "ENV ASSIMVERSION %s\n"	"${ASSIMVERSION}";;
+				  service)			printf 'RUN %s'					"$word $morestuff"
+				  					suck_up_remaining_tasks;;
+				  *)				printf 'RUN %s\n'				"$word $morestuff";;
+				esac
+            done
+			)
+			printf '\n'
+	done
+}
+
+suck_up_remaining_tasks() {
+	while
+		read word morestuff
+	do
+		case $word in
+		  \#*)				;;	# Can't tolerate comments here
+		  *)				printf ' && %s'				"$word $morestuff";;
+		esac
+	done
+	printf '\n'
+}
+
+
+known_tasks() {
+    step_map | cut -d' ' -f1
+}
+
+is_known_task() {
+    step_map | grep -q "^$1 "
+}
+
+test_thyself() {
+    # The set -e will cause us to fail if any tasks aren't known
+	for cmd in create_task_script create_dockerfile create_doxygen_docs create_asciidoc
+	do
+		for task in $(known_tasks)
+		do
+			echo "################# $cmd output for task $task #########################"
+			$cmd "$task"
+		done
+	done
+}
+
+usage() {
+cat <<-!USAGE >&2
+	Usage: $0 [--format={dockerfile|script|doxygen)] task-name
+    $0 generates scripts to perform Assimilation installation tasks for CentOS6/RHEL6
+	Known tasks are:
+	$(known_tasks | sed 's%^%	%')
+	!USAGE
+    exit 1
+}
+format=script
+case $1 in
+ --format=dockerfile)	cmd=create_dockerfile;		shift;;
+ --format=script)		cmd=create_task_script; 	shift;;
+ --format=doxygen)		cmd=create_doxygen_docs; 	shift;;
+ --format=asciidoc)		cmd=create_asciidoc; 		shift;;
+ --format=test)			cmd=test_thyself; 			shift;;
+esac
+
+if
+    [ $# -ne 1 ]
+then
+    usage
+fi
+if
+    is_known_task "$1"
+then
+    : Glad to know that $1 is a known task
+else
+    usage
+fi
+$cmd "$1"
+exit $?
